print("Welcome to the Band Name Generator.")
place = input("What's the name of the city you grew up in?\n")
pet = input("What's your pet's name?\n")
print("Your band name could be "+place+" "+pet)
a = str(len(place+pet)+1)
print("Length of the name is "+a)
a = int(a)
print(a)